### PR TITLE
Improved the project overview

### LINKED ISSUE #1: Improve the Project Overview part in Readme File
Make it more detailed

### PR DESCRIPTION
**Pull request by Abhishek022001**
PR name: Improved the project overview

PR description:   #1  

Short summary

This pull request is to improve the Project overview section 

Name: Detailed project Overview

Description: Fixes #1

Made a detailed project overview section in the READ.ME FILE

Issue Number- #1 

Short Summary

Better readability of Project overview section, and added more details

### CODE REVIEW

**Comment by SGCODEX** [comment]
Great work @Abhishek022001, The project overview looks way better.
Please just edit your PR according to the PR Template we are following: https://github.com/SGCODEX/Music-Recommendation-Using-Facial-Expressions/blob/main/CONTRIBUTING.md#pr-template

**Comment by Abhishek022001** [comment]
Please check now if its okay

**Comment by SGCODEX** [comment]
Heyy, I think there is a little bit confusion.
I meant like this:

Title: Improved the project overview
Fixes #1 
Improved project overview section in the READ.ME FILE

**Comment by SGCODEX** [comment]
Thank you!!

**Pull request merged**
